### ISSUE TITLE
Replace the Ulogs Branding to Farmrs-Club

### ISSUE THREAD

**Issue by nirvanaitsolutions** [nirvanaitsolutions/Farmrs-Club#1]
#### Expected behavior

The Home page should display Farmr-Club instead of Ulogs wherever required as shown in Below screenshot.
![Screenshot_from_2019-05-17_15-13-31-1](https://user-images.githubusercontent.com/30573340/58101094-97c8b900-7bfc-11e9-8c3d-987927bede53.png)
![Screenshot_from_2019-05-17_15-13-55](https://user-images.githubusercontent.com/30573340/58101121-a57e3e80-7bfc-11e9-82c5-450da5c08926.png)
![Screenshot_from_2019-05-17_15-14-19](https://user-images.githubusercontent.com/30573340/58101138-ad3de300-7bfc-11e9-8582-4aa9ab369f58.png)

Please contact us In our Discord server before starting with the task!

**Comment by julianmnst** [comment]
I'll get to it ASAP
